### ISSUE TITLE
Unable to find module

### ISSUE THREAD

**Issue by delianides** [asvetliakov/typings-chai-enzyme#1]
I know all of this is still pretty new but I was seeing the following error when running tests.

```
2 import {Assertion} from '~chai/lib/Assertion';
                          ~~~~~~~~~~~~~~~~~~~~~

typings/main/definitions/chai-enzyme/index.d.ts(2,25): error TS2307: Cannot find module '~chai/lib/Assertion'.


5 declare module '~chai/lib/Assertion' {
                 ~~~~~~~~~~~~~~~~~~~~~

typings/main/definitions/chai-enzyme/index.d.ts(5,16): error TS2664: Invalid module name in augmentation, module '~chai/lib/Assertion' cannot be found.
```

I'm using the typings npm tool and have the `enzyme`,`chai`,`react` typings loaded correctly. If I comment out the assertions that use chai specifically then everything runs correctly. 

Any ideas?

**Comment by asvetliakov** [comment]
What version of TS are you using?
is this error in definition or you're trying to import Assertion in your tests?

just tried. it warns about current chai dependency is deprecated, but everything works if i install chai explicitly `typings install chai`
anyway i'll update typings this week

**Comment by delianides** [comment]
Version 1.8.9

This seems to be an error in the definition. Maybe [here](https://github.com/asvetliakov/typings-chai-enzyme/blob/master/index.d.ts#L2)? 

Using the typings tool seems to generate its definitions on-the-fly. This is whats being [generated](https://gist.github.com/38bbeb294d287b67b70e9aeca65a0ab8) and it doesn't look right to me.

**Comment by asvetliakov** [comment]
The definition is correct, this is part of related chai typings (installed by `typings install chai`)

```
// Generated by typings
// Source: https://raw.githubusercontent.com/typed-typings/npm-chai/0b70226aa4ea9c3b37fe1c709db0423f11ed30d8/lib/Assertion.d.ts
declare module '~chai/lib/Assertion' {
export interface AssertionStatic {
  (target?: any, message?: string, stack?: Function): Assertion;
  new (target?: any, message?: string, stack?: Function): Assertion;
}

export interface Assertion extends LanguageChains, NumericComparison, TypeComparison {
```

Are you using any of jetbrains products?

> This is whats being generated and it doesn't look right to me.

What concrete does look wrong? 

You need non ambient chai typings (from npm and without --ambient flag), ambient from DT will not work. Typings should install it automatically (since chai was declared as dependency), but looks like not in this case

**Comment by asvetliakov** [comment]
Although it wasn't error, i updated chai definition so it would get installed automatically again, don't mess with DT typings.

**Comment by idoo** [comment]
Sorry, i can't find solution here :(
Yes, i using IDEA product and have same issue. Can you give instruction step by step?

**Comment by asvetliakov** [comment]
Make sure you have installed chai non ambient typings (from npm repository, not dt)

```
typings install chai --save-dev
```

**Comment by idoo** [comment]
yep, but in this case i have 
`ERROR in [default] /typings/chai-enzyme/chai-enzyme.d.ts:365:7
Invalid module name in augmentation, module '~chai/lib/Assertion' cannot be found.`

**Comment by idoo** [comment]
yep, but in this case i have 
```ERROR in [default] /typings/chai-enzyme/chai-enzyme.d.ts:365:7
Invalid module name in augmentation, module '~chai/lib/Assertion' cannot be found.```

**Comment by asvetliakov** [comment]
can you show your chai typings?

**Comment by Truedrog** [comment]
I have similar issue, my webstorm doesn't recognise chai-enzyme functions e.g. attr()
`expect(renderedComponent).to.have.attr('alt', 'test');`
`Unresolved function or method attr()`

`typings install chai enzyme chai-enzyme -D`

index.d.ts

```
/// <reference path="modules/chai-enzyme/index.d.ts" />
/// <reference path="modules/chai/index.d.ts" />
/// <reference path="modules/enzyme/index.d.ts" />
```

EDIT:

i replaced generated typings in chai-enzyme.d.ts from typings from this repo and it works all now.

**Comment by asvetliakov** [comment]
@Truedrog nothing to do here until webstorm will make normal ts expirience based on tsserver.  :sweat_smile:

**Comment by Truedrog** [comment]
@asvetliakov Should I consider switch to Visual studio?

**Comment by asvetliakov** [comment]
@Truedrog That depends, i just switched to vs code (any other editor (atom for example)/ide including vs studio will be fine too). Though, auto module import in webstorm is really convenient and useful (until ts team will land own solution in 2.0), but it doesn't work good with typings too (useful for project files import though).
You can have still use webstorm, but you need to use ambient typings versions only from DT repository (i.e. you need dt versions of chai and enzyme) and install my typings manually (put it somewhere in your project, for example in manual_typings directory and include it in compiler tsconfig.json/gulp task)/correct it to work with global chai typings.

**Comment by asvetliakov** [comment]
Also, as medium solution you can enable typescript compiler in webstorm ( if you don't want to webstorm compile typescript for you you can put into options something like it: `-p ./ --noEmit`) and it should get rid off errors in your files, but you lose completion anyway

**Comment by Truedrog** [comment]
@asvetliakov I just installed and tried vscode. Man, this completion is so awesome.
![screen](https://cloud.githubusercontent.com/assets/1725418/15425334/4e4b9cba-1e90-11e6-81ba-63d61e5985d6.png)
